__title__ = 'protonvpn_gtk'
__description__ = 'Unofficial GTK 3 client for ProtonVPN.'
__url__ = 'https://github.com/karmadonov/protonvpn-gtk'
__version__ = '0.1'
__author__ = 'Kirill Karmadonov'
__author_email__ = 'kirill@live.com'
__license__ = 'GPLv3'
__copyright__ = 'Copyright 2020 Kirill Karmadonov'
